# Generated by Django 3.0.4 on 2020-04-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200404_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='authors',
            field=models.ForeignKey(default='noob', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
