# Generated by Django 3.0.4 on 2020-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200404_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.TextField(default='public'),
        ),
    ]
